#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set root cursor
xsetroot -cursor_name left_ptr &

# Run polybar
$HOME/.config/polybar/launch.sh

# Keyboard layout
setxkbmap tr

# Set wallpaper
nitrogen --restore &

# Start compositor
picom --backend glx &

# Dracula color scheme
bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

